version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: scope
    groups:
      ci-dependencies:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
      ci-major-updates:
        patterns:
        - "*"
        update-types:
        - "major"  
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore"
      prefix-development: "build"
      include: scope
    allow:
      - dependency-type: production
      - dependency-type: development
    versioning-strategy: increase
    groups:
      runtime-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
      dependencies:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
      major-updates:
        patterns:
        - "*"
        update-types:
        - "major"