version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    groups:
      ci-dependencies:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
      ci-major-updates:
        patterns:
        - "*"
        update-types:
        - "major"  
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
    groups:
      dependencies:
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
      major-updates:
        patterns:
        - "*"
        update-types:
        - "major"
